### ISSUE TITLE
User Creation Form 

### ISSUE THREAD

**Issue by shassaan** [shassaan/images-dashboard-frontend#15]
**Feature**
A User Creation Form 

**Description**
A Simple form with fields **full name, email, password, dob, Access Roles**

**Access Roles**
a list of checkboxes to assign multiple Roles to users.

**Comment by shassaan** [comment]
looking forward to it 
it will have sidebar  link and on clicking on the link you will render this form make

@sjaveriawasti

**Comment by shassaan** [comment]
@sjaveriawasti  you did not follow proper directory structure
you added layout from inside layout
design of form needs improvement

pull all changes from master than do the required changes

**Comment by sjaveriawasti** [comment]
In which file I did this?

**Comment by sjaveriawasti** [comment]
@shassaan

**Comment by shassaan** [comment]
From component should have a folder with css file @sjaveriawasti  and all styles will be in css file not inline

**Comment by shassaan** [comment]
Please convert this screen the same as the role management screen and add the search bar on top of the user's list.

@sjaveriawasti
